// Generated by https://quicktype.io

export interface FlyBondyTravels {
  data: string;
  origin: "BRC" | "COR" | "EPA" | "MDZ";
  destination: "BRC" | "COR" | "EPA" | "MDZ";
  price: number;
  availability: number;
}
