// Generated by https://quicktype.io

export interface FlyBondyTravels {
  data: string;
  origin: Travels;
  destination: Travels;
  price: number;
  availability: number;
}

export type Travels = "BRC" | "COR" | "EPA" | "MDZ";
